services:
  postgresql:
    image: postgres:16
    container_name: meals_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meals_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    restart: unless-stopped
    networks:
      - meals_network
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    #   - ./backend/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  meals_network:
    driver: bridge

volumes:
  postgresql_data: